"use client";

import { useState } from "react";
import { Activity, Check, ChevronRight, Copy, Eye, LockKeyhole, Send, Settings2, ShieldCheck, TriangleAlert, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

declare global { interface Window { ethereum?: { request: (args: { method: string }) => Promise<string[]> } } }
const account = "0x479aa953B3d730588734bacc0dfD9D2Cb7e1C2db";
const policy = "0x0a964BAacbaC37f788c898b2E2FB9680B68179c1";
const short = (v: string) => v.length > 12 ? v.slice(0, 6) + "…" + v.slice(-4) : v;

function Pill({ children, red = false }: { children: React.ReactNode; red?: boolean }) {
  return <span className={"inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold " + (red ? "border-[#f04b48]/30 bg-[#f04b48]/10 text-[#ff8987]" : "border-emerald-300/20 bg-emerald-300/10 text-emerald-300")}>{children}</span>;
}
function Policy({ icon, title, description, value }: { icon: React.ReactNode; title: string; description: string; value: string }) {
  return <article className="rounded-[28px] border border-white/[.09] bg-[#181819] p-6"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-white/[.06] text-[#ff7774]">{icon}</div><Pill><Check className="size-3" />{value}</Pill></div><h3 className="mt-7 text-xl font-medium tracking-[-.04em]">{title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{description}</p><button className="mt-7 flex items-center gap-2 text-sm text-white/65 hover:text-white">Manage policy <ChevronRight className="size-4" /></button></article>;
}
export default function Home() {
  const [wallet, setWallet] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [amount, setAmount] = useState("0.20");
  const [recipient, setRecipient] = useState("");
  const [review, setReview] = useState(false);
  const total = Number(amount) || 0;
  const blocked = total > 1;
  async function connect() {
    if (!window.ethereum) { setMessage("Install MetaMask to connect an owner wallet."); return; }
    try { const values = await window.ethereum.request({ method: "eth_requestAccounts" }); setWallet(values[0] ?? null); setMessage(""); } catch { setMessage("Wallet connection was cancelled."); }
  }
  return <main className="min-h-screen bg-[#0d0d0e] text-white selection:bg-[#e63735]">
    <div className="mx-auto flex min-h-screen max-w-[1500px]">
      <aside className="hidden w-[248px] shrink-0 flex-col border-r border-white/[.08] bg-[#111112] px-5 py-7 lg:flex"><div className="flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-2xl bg-[#e63735]"><ShieldCheck className="size-5" /></div><span className="text-xl font-semibold tracking-[-.06em]">paranoia</span></div><nav className="mt-12 space-y-2">{[[WalletCards,"Wallet"],[Send,"Send"],[Activity,"Activity"],[Settings2,"Policies"]].map(([Icon,label], i) => <button key={String(label)} className={"flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm " + (i === 0 ? "bg-white/[.09]" : "text-white/45 hover:bg-white/[.05] hover:text-white")}><Icon className="size-[18px]" />{String(label)}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><LockKeyhole className="size-4 text-[#ff7774]" /><p className="mt-3 text-sm font-medium">Security is on-chain</p><p className="mt-1 text-xs leading-5 text-white/45">Policies execute inside your smart account.</p></div></aside>
      <section className="min-w-0 flex-1 px-4 py-4 sm:px-7 sm:py-7 lg:px-10">
        <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3 lg:hidden"><div className="grid size-10 place-items-center rounded-2xl bg-[#e63735]"><ShieldCheck className="size-5" /></div><span className="text-xl font-semibold tracking-[-.06em]">paranoia</span></div><div className="hidden lg:block"><p className="text-sm text-white/45">Celo Sepolia</p><h1 className="mt-1 text-2xl font-medium tracking-[-.05em]">Your protected wallet</h1></div>{wallet ? <div className="flex items-center gap-2 rounded-2xl border border-white/[.1] bg-white/[.05] px-3 py-2.5 text-sm"><span className="size-2 rounded-full bg-emerald-400" />{short(wallet)}</div> : <Button onClick={connect} className="h-11 rounded-2xl bg-white px-5 font-semibold text-black hover:bg-white/85">Connect wallet</Button>}</header>
        {message && <p className="mt-3 text-sm text-[#ff8987]">{message}</p>}
        <Tabs defaultValue="wallet" className="mt-7 sm:mt-10"><TabsList className="h-auto gap-1 rounded-xl border border-white/[.08] bg-white/[.035] p-1"><TabsTrigger value="wallet" className="rounded-lg px-4 py-2 data-[state=active]:bg-white data-[state=active]:text-black">Wallet</TabsTrigger><TabsTrigger value="send" className="rounded-lg px-4 py-2 data-[state=active]:bg-white data-[state=active]:text-black">Send</TabsTrigger><TabsTrigger value="security" className="rounded-lg px-4 py-2 data-[state=active]:bg-white data-[state=active]:text-black">Security</TabsTrigger></TabsList>
          <TabsContent value="wallet" className="mt-7 outline-none"><div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.72fr)]"><article className="relative overflow-hidden rounded-[28px] border border-white/[.09] bg-[#181819] p-6 sm:p-9"><div className="pointer-events-none absolute -right-24 -top-28 size-72 rounded-full bg-[#e63735]/20 blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><p className="text-sm text-white/50">Total balance</p><h2 className="mt-3 text-5xl font-medium tracking-[-.075em] sm:text-7xl">0.00 <span className="text-2xl text-white/40 sm:text-3xl">CELO</span></h2><p className="mt-3 text-sm text-white/42">Fund this account to begin using Paranoia.</p></div><Pill><Check className="size-3" />PROTECTED</Pill></div><div className="relative mt-10 flex flex-wrap gap-3"><button onClick={() => navigator.clipboard?.writeText(account)} className="flex items-center gap-2 rounded-xl border border-white/[.1] bg-black/20 px-3 py-2.5 text-xs text-white/65 hover:text-white"><Copy className="size-3.5" />{short(account)}</button><a href={"https://celo-sepolia.blockscout.com/address/" + account} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl border border-white/[.1] bg-black/20 px-3 py-2.5 text-xs text-white/65 hover:text-white"><Eye className="size-3.5" />Explorer</a></div></article><article className="rounded-[28px] border border-white/[.09] bg-[#181819] p-6"><div className="flex justify-between"><p className="text-sm font-medium">Security status</p><ShieldCheck className="size-5 text-[#ff6b68]" /></div><div className="mt-7 space-y-5">{[["ERC-4337 account","ACTIVE"],["Spending limit","1 CELO"],["Approval protection","ACTIVE"],["EIP-7702 delegation","SCAN"]].map(([name,value], i) => <div key={name} className="flex items-center justify-between"><span className="text-sm text-white/55">{name}</span>{i < 3 ? <Pill><Check className="size-3" />{value}</Pill> : <span className="text-xs text-white/45">{value}</span>}</div>)}</div></article></div><div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.72fr)]"><article className="rounded-[28px] border border-white/[.09] bg-[#181819] p-6 sm:p-7"><div className="flex justify-between"><div><p className="text-lg font-medium tracking-[-.035em]">Recent activity</p><p className="mt-1 text-sm text-white/42">Your protected account is ready.</p></div><Activity className="size-5 text-white/35" /></div><div className="mt-7 rounded-2xl border border-dashed border-white/[.12] px-5 py-8 text-center text-sm text-white/52">No transactions yet</div></article><article className="rounded-[28px] bg-[#e63735] p-6"><Send className="size-5" /><p className="mt-8 text-2xl font-medium leading-tight tracking-[-.055em]">Send CELO with a security check.</p></article></div></TabsContent>
          <TabsContent value="send" className="mt-7 outline-none"><div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(350px,.9fr)]"><section className="rounded-[28px] border border-white/[.09] bg-[#181819] p-6 sm:p-8"><p className="text-sm text-white/45">New transfer</p><h2 className="mt-2 text-3xl font-medium tracking-[-.055em]">Send CELO securely</h2><label className="mt-8 block text-sm text-white/55">Recipient<input value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="0x…" className="mt-2 w-full rounded-2xl border border-white/[.1] bg-black/25 px-4 py-4 text-base text-white outline-none placeholder:text-white/25" /></label><label className="mt-5 block text-sm text-white/55">Amount<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.1] bg-black/25 px-4 py-4 text-2xl text-white outline-none" /></label><Button onClick={() => setReview(true)} className="mt-6 h-13 w-full rounded-2xl bg-[#e63735] text-base hover:bg-[#f04744]">Review transaction</Button></section><article className={"rounded-[28px] border p-6 sm:p-8 " + (blocked ? "border-[#f04b48]/30 bg-[#271617]" : "border-white/[.09] bg-[#181819]")}><div className="flex justify-between"><p className="text-sm text-white/50">Policy simulation</p>{blocked ? <TriangleAlert className="size-5 text-[#ff8987]" /> : <ShieldCheck className="size-5 text-emerald-300" />}</div><p className="mt-7 text-4xl font-medium tracking-[-.065em]">{blocked ? "BLOCKED" : "SAFE"}</p><p className="mt-3 text-sm leading-6 text-white/52">{blocked ? total.toFixed(2) + " CELO exceeds your configured 1 CELO limit." : "This transfer stays within your configured spending limit."}</p></article></div></TabsContent>
          <TabsContent value="security" className="mt-7 outline-none"><div className="grid gap-5 lg:grid-cols-2"><Policy icon={<WalletCards className="size-5" />} title="Native spending limit" description="Maximum CELO that can leave the account in one transaction." value="1 CELO" /><Policy icon={<LockKeyhole className="size-5" />} title="Unlimited approvals" description="approve(spender, MAX_UINT256) is blocked before execution." value="ACTIVE" /><Policy icon={<ShieldCheck className="size-5" />} title="Trusted contracts" description="Unknown targets are visibly flagged before you continue." value="0 TRUSTED" /><Policy icon={<Settings2 className="size-5" />} title="EIP-7702 delegates" description="Paranoia only submits proposed delegates from your allowlist." value="0 ALLOWLISTED" /></div><div className="mt-5 rounded-[28px] border border-white/[.09] bg-[#181819] p-6"><p className="text-sm text-white/45">Policy manager</p><p className="mt-2 font-mono text-sm text-white/75">{policy}</p></div></TabsContent>
        </Tabs>
      </section>
    </div>
    <Dialog open={review} onOpenChange={setReview}><DialogContent className="border-white/[.12] bg-[#171718] p-6 text-white sm:max-w-[480px]"><DialogHeader><DialogTitle className="text-2xl tracking-[-.045em]">Transaction review</DialogTitle><DialogDescription className="text-white/45">Paranoia checks this request before it reaches the EntryPoint.</DialogDescription></DialogHeader><div className="rounded-2xl bg-black/25 p-4 text-sm"><div className="flex justify-between"><span className="text-white/45">Send</span><span>{total.toFixed(2)} CELO</span></div><div className="mt-3 flex justify-between"><span className="text-white/45">To</span><span>{recipient ? short(recipient) : "Recipient required"}</span></div></div><div className={"rounded-2xl border p-4 " + (blocked ? "border-[#f04b48]/25 bg-[#f04b48]/10" : "border-emerald-300/20 bg-emerald-300/10")}><p className="font-medium">{blocked ? "Transaction blocked" : "Safe to submit"}</p><p className="mt-1 text-sm text-white/55">{blocked ? "SPENDING_LIMIT_EXCEEDED — this transfer is above your 1 CELO limit." : "The transfer is within your 1 CELO spending limit."}</p></div><DialogFooter><Button onClick={() => setReview(false)} disabled={blocked || !recipient} className="h-11 rounded-xl bg-white text-black hover:bg-white/85">{blocked ? "Blocked by policy" : "Continue with wallet"}</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}
